if(${TARGET} STREQUAL "stm32f4")
    add_subdirectory(lcd_printer)
    add_subdirectory(wave_measure)
    add_subdirectory(pulse_measure)
    add_subdirectory(wave_starter)
    add_subdirectory(diskio_drivers)
    add_subdirectory(usb_service)
    add_subdirectory(cli_service)
    add_subdirectory(config_service)
    add_subdirectory(status_service)
elseif(${TARGET} STREQUAL "stm32f7")
    add_subdirectory(diskio_drivers)
    add_subdirectory(usb_service)
    add_subdirectory(cli_service)
    add_subdirectory(config_service)
    add_subdirectory(status_service)
else()
    message(FATAL_ERROR "unsupported target ${TARGET}")
endif()
