#include "cli_service.h"
#include "cli_commands.h"
#include "cli_commands_fs.h"
#include "cli_commands_app.h"
#include "FreeRTOS.h"

#define MAX_INPUT_LENGTH    32
#define MAX_OUTPUT_LENGTH   1024

void cli_task(void* param){
    int cRxedChar;
	BaseType_t cInputIndex = 0;
	BaseType_t xMoreDataToFollow;
	/* The input and output buffers are declared static to keep them off the stack. */
	static char pcOutputString[ MAX_OUTPUT_LENGTH ], pcInputString[ MAX_INPUT_LENGTH ];

    while(1){
		/* This implementation reads a single character at a time.  Wait in the
		Blocked state until a character is received. */

        cRxedChar = debug_console_getchar();

    if (cRxedChar != -1){
        char echo_buf[2] = {(char)cRxedChar, '\0'};
		if( cRxedChar == '\r' )
		{
			/* A newline character was received, so the input command string is
			complete and can be processed.  Transmit a line separator, just to
			make the output easier to read. */
			print_raw("\n\r");

			/* The command interpreter is called repeatedly until it returns
			pdFALSE.  See the "Implementing a command" documentation for an
			exaplanation of why this is. */
			do
			{
				/* Send the command string to the command interpreter.  Any
				output generated by the command interpreter will be placed in the
				pcOutputString buffer. */
				xMoreDataToFollow = FreeRTOS_CLIProcessCommand
							  (
								  pcInputString,   /* The command string.*/
								  pcOutputString,  /* The output buffer. */
								  MAX_OUTPUT_LENGTH/* The size of the output buffer. */
							  );

				/* Write the output generated by the command interpreter to the
				console. */
				print_raw(pcOutputString);
				memset(pcOutputString, 0, MAX_OUTPUT_LENGTH);

			} while( xMoreDataToFollow != pdFALSE );
			print_raw(">>");

			/* All the strings generated by the input command have been sent.
			Processing of the command is complete.  Clear the input string ready
			to receive the next command. */
			cInputIndex = 0;
			memset( pcInputString, 0x00, MAX_INPUT_LENGTH );
		}
		else
		{
			/* The if() clause performs the processing after a newline character
			is received.  This else clause performs the processing if any other
			character is received. */

			if( cRxedChar == '\n' )
			{
				/* Ignore carriage returns. */
			}
			//else if( cRxedChar == '\b' )
			else if( cRxedChar == 0x7F )
			{
				/* Backspace was pressed.  Erase the last character in the input
				buffer - if there are any. */
				if( cInputIndex > 0 )
				{
					cInputIndex--;
					pcInputString[ cInputIndex ] = (char)'\0';
					print_raw(echo_buf);
				}
			}
			else
			{
				/* A character was entered.  It was not a new line, backspace
				or carriage return, so it is accepted as part of the input and
				placed into the input buffer.  When a \n is entered the complete
				string will be passed to the command interpreter. */
				if( cInputIndex < MAX_INPUT_LENGTH )
				{
					pcInputString[ cInputIndex ] = cRxedChar;
					cInputIndex++;
				}
				print_raw(echo_buf);
			}
		}
    }
        vTaskDelay(10 / portTICK_PERIOD_MS);
	}
}

void cli_service_init(void){
    CLI_install_commands();
	CLI_install_commands_fs();
    CLI_install_commands_app();
    xTaskCreate(cli_task,  "cli_task", configMINIMAL_STACK_SIZE * 2, NULL, 1, NULL);
}